services:
  matchmaking:
    build: ./matchmaking
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/matchmaking_db
    depends_on:
      - db

  game-session:
    build: ./game-session
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/game_session_db
    depends_on:
      - db

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gateway_db
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ALL_DBS: matchmaking_db,game_session_db,gateway_db
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
