spring:
  application:
    name: game-services-gateway
  datasource:
    url: jdbc:postgresql://postgres-db:5432/gateway_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: INFO
    com.dharmit.game_services: DEBUG
    org.hibernate.SQL: DEBUG
    liquibase: INFO

jwt:
  secret: ${JWT_SECRET:verySecureSecretKeyThatShouldBeChangedInProduction}
  expiration: 24h

microservices:
  matchmaking:
    url: ${MATCHMAKING_URL:http://matchmaking:8081}
  game-session:
    url: ${GAME_SESSION_URL:http://game-session:8082}
