apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-session-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-session
  template:
    metadata:
      labels:
        app: game-session
    spec:
      containers:
        - name: game-session
          imagePullPolicy: IfNotPresent
          image: game-session:latest
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
