spring:
  application:
    name: game-services-matchmaking
  datasource:
    url: jdbc:postgresql://postgres-db:5432/matchmaking_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8081

logging:
  level:
    root: INFO
    com.dharmit.game_services: DEBUG
    org.hibernate.SQL: DEBUG
    liquibase: INFO

jwt:
  secret: ${JWT_SECRET:verySecureSecretKeyThatShouldBeChangedInProduction}
  expiration: ${JWT_EXPIRATION:24h}
