spring:
  application:
    name: game-services-game-session
  datasource:
    url: jdbc:postgresql://postgres-db:5432/game_session_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082

# Logging configuration
logging:
  level:
    root: INFO
    com.dharmit.game_services: DEBUG
    org.hibernate.SQL: DEBUG
    liquibase: INFO
