spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/game_session_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 8082

# Logging for local development
logging:
  level:
    root: INFO
    com.dharmit.game_services: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    liquibase: INFO
